version: 2.1
orbs:
  architect: giantswarm/architect@5.1.2

workflows:
  go-build:
    jobs:
      - architect/go-test:
          name: go-test-gitrepo
          # Needed to trigger job also on git tag.
          filters:
            tags:
              only: /^v.*/
